### ISSUE TITLE
SAE Memcache无法使用

### ISSUE THREAD

**Issue by lzz5235** [Xiderowg/WordPress-For-Sae#1]
Warning: Memcache::setcompressthreshold(): No servers added to memcache connection in /data1/www/htdocs/622/..../1/wp-content/object-cache.php on line 381

Warning: Memcache::get(): No servers added to memcache connection in /data1/www/htdocs/622/...../1/wp-content/object-cache.php on line 212

Warning: Memcache::get(): No servers added to memcache connection in /data1/www/htdocs/622/...../1/wp-content/object-cache.php on line 212

Warning: Memcache::add(): No servers added to memcache connection in /data1/www/htdocs/622/...../1/wp-content/object-cache.php on line 121

Warning: Memcache::set(): No servers added to memcache connection in /data1/www/htdocs/622/...../1/wp-content/object-cache.php on line 303

**Comment by Xiderowg** [comment]
这个插件集成了Memcache，得开启Memcache，或者直接删除object-cache.php插件也是可以运行的

**Comment by Xiderowg** [comment]
才看到是WP FOR SAE的....Memcache开启了吗？报这个错误的原因一般是Memcache没有开启，如果开启了，到SAE应用管理使用应用自检看一下Memcache的服务状态，还是不行可以试试看在Memcache状态页清空缓存后禁用Memcache再开启Memcache

**Comment by Xiderowg** [comment]
再不然就调高memcache的容量，感谢您的反馈

**Comment by lzz5235** [comment]
我刚才进行了服务质检

检查 Memcache
MC建立链接 ································ 成功
MC设置值操作(memcache_set) ································ 成功
MC读取值操作(memcache_get) ································ 成功
Memcache检查完成,服务正常
检查 完毕！

Memcache应该没有问题，按照你的方式试了下，但是仍然出现这个错误，容量调为50M，没有效果，看来只能先删除这个插件了。

**Comment by Xiderowg** [comment]
修改了一下object-cache.php的代码，使用官方的API，麻烦您测试一下

**Comment by lzz5235** [comment]
不知是否是缓存原因，一直是不返回数据，页面为空

**Comment by Xiderowg** [comment]
到应用后台Flush一下Memcache的缓存，在我这边代码是测试通过的

**Comment by lzz5235** [comment]
clone 你的最新代码，重新部署：
Parse error: syntax error, unexpected ':' in /data1/www/htdocs/622/...../4/wp-config.php on line 23

**Comment by Xiderowg** [comment]
请手动吧wp-config.php的22和23行替换成
define('SAE_DIR','saestor://'.SAE_STORAGE.'/uploads');
define('SAE_URL', 'http://'.$_SERVER['HTTP_APPNAME'].'-'.SAE_STORAGE.'.stor.sinaapp.com/uploads');
编辑的时候不小心自动转换成全角了，SAE的SDK被我删了不好管理生产环境，问题可能会有点多，不好意思

**Comment by lzz5235** [comment]
谢谢您的帮助，我已解决这个问题。
